### PR TITLE
Fix date/time box in eventDetailsScreen

### LINKED ISSUE #276: Fix eventDetailsScreen date/time container bug

### PR DESCRIPTION
**Pull request by KianBahia**
## Overview
Fix event details screen layout bug where sometimes the container height filled the full screen and added parsing of event date and time. 

### Description changes
- Added `wrapContentHeight()` and reduced `fillMaxSize()` to prevent the container from taking the full screen height
- Added formatting to split the `event.time` into separate date and time fields

The images below show the container with the date and time separated.
image
image

This directly addresses issue #276 by fixing the container bug

### CODE REVIEW

File: app/src/androidTest/java/ch/epfllife/ui/EventDetailsScreenTest.kt [hunk 1]
```diff
@@ -80,15 +85,48 @@ class EventDetailsScreenTest {
...
-    composeTestRule.onAllNodesWithText("2025-10-12 18:00")[0].assertIsDisplayed()
+    composeTestRule.onNodeWithText("2025-10-12").assertIsDisplayed()
+    composeTestRule.onNodeWithText("18:00").assertIsDisplayed()
+  }
+
+  @Test
+  fun timeWithDash_isFormattedWithColon() {
+    val dashedEvent = sampleEvent.copy(time = "2025-10-12 07-30")
+    setSuccessContent(dashedEvent)
+    composeTestRule.onNodeWithText("07:30").assertIsDisplayed()
```
Comment (pukoa420) [inline app/src/androidTest/java/ch/epfllife/ui/EventDetailsScreenTest.kt]: Could we remove hardcoded values and maybe somehow use the centralized example test data?

**Review by pukoa420 — APPROVED** [review]
Nice PR!
- updated and cleaner tests
- formating time and date before displaying is a good approach and ensures "too much text" bug is mitigated
- removing the Preview is good as its not necessary anymore and has hardcoded values

**Review by pukoa420 — APPROVED** [review]
Improved handling of test data. (+previously mentioned content)
=> ready to merge
